import {
    Currency,
    EmailTemplate,
    Employee,
    Feature,
    FeatureOrganization,
    Invite,
    Organization,
    OrganizationTeam,
    OrganizationTeamEmployee,
    Role,
    RolePermission,
    Tenant,
    User,
    UserOrganization,
} from './internal';

export const coreEntities = [
    Currency,
    EmailTemplate,
    Employee,
    Feature,
    FeatureOrganization,
    Invite,
    Organization,
    OrganizationTeam,
    OrganizationTeamEmployee,
    Role,
    RolePermission,
    Tenant,
    User,
    UserOrganization,
];
